version: 2
jobs:
  build:
    machine: true
    working_directory: ~/dotfiles
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
             sudo add-apt-repository ppa:jonathonf/vim
             sudo apt-get update
             sudo apt-get install zsh
             sudo apt-get install vim
      - run:
          name: setup
          command: |
             ./setup.sh
             zsh -c 'exit'
      - run:
          name: test
          command: |
              zsh -c 'exit'
              vim +qa

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
