version: 2
jobs:
  build:
    machine: true
    working_directory: ~/dotfiles
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
             sudo add-apt-repository -y ppa:fcwu-tw/ppa
             sudo apt-get update
             sudo apt-get install zsh
             sudo apt-get install vim
          working_directory: dotfiles
      - run:
          name: setup
          command: |
             ./setup.sh
             zsh -c 'exit'
             yes|vim +qall
          working_directory: dotfiles
      - run:
          name: test
          command: |
              zsh -c 'exit'
              yes|vim +qall
          working_directory: dotfiles

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
