# yaml-language-server: $schema=https://json.schemastore.org/circleciconfig.json
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/dotfiles
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            sudo add-apt-repository ppa:jonathonf/vim
            sudo add-apt-repository ppa:neovim-ppa/unstable
            sudo apt-get update
            sudo apt-get install zsh
            sudo apt-get install vim
            sudo apt-get install neovim
            sudo apt-get install nodejs
            sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
            sudo apt-get install golang
            go get github.com/rhysd/vim-startuptime
      - run:
          name: setup
          command: |
            ./setup.sh
            zsh -c 'exit'
      - run:
          name: test
          command: |
            zsh -c 'exit'
            vim +qa
            echo vim startup time[ms]:;vim-startuptime | egrep 'Total Average' |awk '{print $3}'
            echo nvim startup time[ms]:;vim-startuptime -vimpath nvim|egrep 'Total Average' |awk '{print $3}'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
