# yaml-language-server: $schema=https://json.schemastore.org/circleciconfig.json
version: 2
jobs:
  build:
    machine: true
    working_directory: ~/dotfiles
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            sudo add-apt-repository ppa:jonathonf/vim
            sudo apt-get update
            sudo apt-get install zsh
            sudo apt-get install vim
            sudo apt-get install node
            sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
            sudo apt-get install golang
            go get github.com/rhysd/vim-startuptime
      - run:
          name: setup
          command: |
            ./setup.sh
            zsh -c 'exit'
      - run:
          name: test
          command: |
            zsh -c 'exit'
            vim +qa
            vim-startuptime | egrep 'Total Average' |awk '{print $3}'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
