version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:edge
    working_directory: ~/dotfiles
    steps:
      - checkout
      - run:
          name: Add GPG keys and repositories
          command: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:jonathonf/vim
            sudo add-apt-repository -y ppa:heroku/ubuntu
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E88979FB9B30ACF2
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 868C56076B935C6E
            sudo rm -f /etc/apt/sources.list.d/google.list
      - run:
          name: Update and install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y zsh vim neovim nodejs
      - run:
          name: Install Rust
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run:
          name: Install Go
          command: |
            sudo snap install --classic go
      - run:
          name: Install other tools
          command: |
            sudo go install github.com/rhysd/vim-startuptime@latest
            sudo apt-get install -y cpanminus
            sudo cpanm App::St
      - run:
          name: Setup
          command: |
            ./setup.sh
            zsh -c 'exit'
      - run:
          name: Test
          command: |
            zsh -c 'exit'
            vim +qa
            echo vim startup time[ms]:;sudo /root/go/bin/vim-startuptime | egrep 'Total Average' |awk '{print $3}'
            echo nvim startup time[ms]:;sudo /root/go/bin/vim-startuptime -vimpath nvim|egrep 'Total Average' |awk '{print $3}'
            echo zsh startup time[sec];./bin/zshbench

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
