version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Update package lists
          command: sudo apt-get update
      - run:
          name: Install required packages
          command: |
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:jonathonf/vim
            sudo apt-get update
            sudo apt-get install -y zsh vim neovim nodejs
      - run:
          name: Install Rust
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
            echo 'source $HOME/.cargo/env' >> $BASH_ENV
      - run:
          name: Install Go
          command: |
            sudo apt-get install -y wget
            wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
            echo 'export PATH=$PATH:/usr/local/go/bin' >> $BASH_ENV
            echo 'export GO111MODULE=on' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install other tools
          command: |
            go install github.com/rhysd/vim-startuptime@latest
            sudo apt-get install -y cpanminus
            sudo cpanm App::St
      - run:
          name: Setup
          command: |
            ./setup.sh
            zsh -c 'exit'
      - run:
          name: Test
          command: |
            zsh -c 'exit'
            vim +qa
            echo vim startup time[ms]:;vim-startuptime | egrep 'Total Average' |awk '{print $3}'
            echo nvim startup time[ms]:;vim-startuptime -vimpath nvim|egrep 'Total Average' |awk '{print $3}'
            echo zsh startup time[sec];./bin/zshbench

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
