# yaml-language-server: $schema=https://json.schemastore.org/circleciconfig.json
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/dotfiles
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            sudo add-apt-repository ppa:jonathonf/vim
            sudo add-apt-repository ppa:neovim-ppa/unstable
            sudo apt update
            sudo apt install zsh
            sudo apt install vim
            sudo apt install neovim
            sudo apt install nodejs
            sudo curl https://sh.rustup.rs -sSf | sh -s -- -y
            sudo snap install --classic go
            sudo go install github.com/rhysd/vim-startuptime@latest
            sudo apt-get install cpanminus
            sudo cpanm App::St
      - run:
          name: setup
          command: |
            ./setup.sh
            zsh -c 'exit'
      - run:
          name: test
          command: |
            zsh -c 'exit'
            vim +qa
            echo vim startup time[ms]:;sudo /root/go/bin/vim-startuptime | egrep 'Total Average' |awk '{print $3}'
            echo nvim startup time[ms]:;sudo /root/go/bin/vim-startuptime -vimpath nvim|egrep 'Total Average' |awk '{print $3}'
            echo zsh startup time[sec];./bin/zshbench
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
