#!/usr/bin/env zsh
self=$0

function $self::getClusterIP() {
:
}

kubectl get svc | selector --prompt "[$0]"| awk '{print $1}'|egrep -v 'NAME.+CLUSTER-IP'|sort | uniq | \
  pecoAfterAction \
    "kubectl describe svc " \
    "kubectl get svc " \
    "kubectl get svc --output=json " \
    "kubectl get svc --output=yaml " \
    "$self::getClusterIP " \
    "%%STDIN%% cat" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% pecoPipe" \
    "%%STDIN%% paaPbCopy"
