#!/usr/bin/env zsh
self=$0

function $self::getClusterIP() {
# TODO: implement this
:
}

kubectl get svc --all-namespaces=true| selector --prompt "[$0]"| awk '{print $1, $2}'|egrep -v 'NAME.+CLUSTER-IP'|sort | uniq | \
  pecoAfterAction \
    "kubectl describe svc -n " \
    "kubectl get svc -n " \
    "kubectl get svc --output=json -n " \
    "kubectl get svc --output=yaml -n " \
    "$self::getClusterIP " \
    "%%STDIN%% cat " \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% pecoPipe" \
    "%%STDIN%% paaPbCopy"
