#!/usr/bin/env zsh
#概要：known_hostsなどからssh先をpecoして接続する

# source action define
function $self::_sshSourceAction() {
  # candidates was written by NAKAMURA Yoshitaka
  # Copyright (c) 2011, NAKAMURA Yoshitaka
  # All rights reserved. BSD-3.
  # https://github.com/zsh-users/zaw/blob/master/LICENSE
  local -a _global_ssh_known_hosts _global_ssh_known_hosts2 _ssh_known_hosts _ssh_known_hosts2 _etc_hosts _ssh_config_hosts
  [ -r /etc/ssh/ssh_known_hosts ] && _global_ssh_known_hosts=(${${${(f)"$(< /etc/ssh/ssh_known_hosts)"}%%\ *}%%,*}) 2>/dev/null || _global_ssh_known_hosts=()
  [ -r /etc/ssh/ssh_known_hosts2 ] && _global_ssh_known_hosts2=(${${${(f)"$(< /etc/ssh/ssh_known_hosts2)"}%%\ *}%%,*}) 2>/dev/null || _global_ssh_known_hosts2=()
  [ -r "$HOME/.ssh/known_hosts" ] && _ssh_known_hosts=(${${${(f)"$(< ~/.ssh/known_hosts)"}%%\ *}%%,*}) 2>/dev/null || _ssh_known_hosts=()
  [ -r "$HOME/.ssh/known_hosts2" ] && _ssh_known_hosts2=(${${${(f)"$(< ~/.ssh/known_hosts2)"}%%\ *}%%,*}) 2>/dev/null || _ssh_known_hosts2=()
  [ -r /etc/hosts ] && : ${(A)_etc_hosts:=${(s: :)${(ps:\t:)${${(f)~~"$(</etc/hosts)"}%%\#*}##[:blank:]#[^[:blank:]]#}}} || _etc_hosts=()
  [ -r "$HOME/.ssh/config" ] && _ssh_config_hosts=(${${${(@M)${(f)"$(< ~/.ssh/config)"}:#Host *}#Host }:#*[*?]*}) || _ssh_config_hosts=()
  [ -r "$HOME/knowns" ] && _ssh_knowns=( ${(@f)"$(< $HOME/knowns )"} ) || _ssh_knowns=()
  candidates=(
    $_global_ssh_known_hosts[@]
    $_global_ssh_known_hosts2[@]
    $_ssh_known_hosts[@]
    $_ssh_known_hosts2[@]
    $_etc_hosts[@]
    $_ssh_config_hosts[@]
    $_ssh_knowns[@]
    "$HOST"
    ::1
    localhost
    127.0.0.1
  )
  echo $(echo $candidates |perl -pe 's/ /\n/g'|sort |uniq)
}

candidates=($($self::_sshSourceAction))
for candidate in $candidates; do
  echo $candidate
done | selector --prompt "[$0]"| sort | uniq | pecoAfterAction "pssh " \
                              "tcmd sftp " \
                              "tcmd redis-stat " \
                              "%%STDIN%% cat" \
                              "%%STDIN%% paaTovim" \
                              "%%STDIN%% pecoPipe" \
                              "%%STDIN%% paaPbCopy"

