#!/usr/bin/env zsh
#概要： podに対してなにかする やつ
self=$0

function $self::_getIp() {
  while read node;do
    (kubectl get node --output=json $node | gron | fgrep 'status.addresses[0].address'|awk '{print $NF}'|perl -pe 's/[";]//g') &
  done
  wait
}
function $self::_convertPodToNode() {
  while read pod ;do
    (kubectl get po $pod -o wide | awk '{print $NF}' |egrep -v '^NODE$') &
  done
  wait
}
function $self::nodeSsh() {
  $self::_convertPodToNode | sort | uniq  | $self::_getIp | pecoAfterAction "pssh "
}

function $self::_k8sSh() {
  pods=("$@")
  tcmd kubectlSh $pods
}

function $self::k8sSh() {
  pecoAfterAction "$self::_k8sSh "
}

function $self::k8sPortForward() {
	local podName=$1
	if [[ -z $podName ]]
	then
		return 1
	fi
	local port=$(kubectl get pod --output=json $podName |gron |grep -i containerport |perl -pe 's/.+=|;//g'|perl -pe 's/ //g')
	echo kubectl port-forward $podName $port:$port
	kubectl port-forward $podName $port:$port
}

function $self::k8sGetPodIP() {
	local podName=$1
	if [[ -z $podName ]]
	then
		return 1
	fi
  kubectl get pod --output=json $podName |gron|grep -i podip | perl -pe 's/.+=|;//g'|perl -pe 's/ //g' | perl -pe 's/"//g'
}

function $self::k8sGetPodIPToPbcopy() {
	local podName=$1
	if [[ -z $podName ]]
	then
		return 1
	fi
  podIp=$($self::k8sGetPodIP $podName)
  echo "pbcopied " $podIp
  echo $podIp | pbcopy
}

kubectl get po -o wide --all-namespaces=true| selector --prompt "[$0]"| awk '{print $2}'|sort | uniq | \
  pecoAfterAction \
    "kubectl describe pod " \
    "kubectl logs " \
    "kubectl logs -f " \
    "kubectl get pod " \
    "kubectl get pod --output=json " \
    "kubectl get pod --output=yaml " \
    "$self::k8sGetPodIP " \
    "$self::k8sPortForward " \
    "$self::k8sGetPodIPToPbcopy " \
    "%%STDIN%% $self::k8sSh" \
    "%%STDIN%% $self::nodeSsh" \
    "%%STDIN%% cat" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% pecoPipe" \
    "%%STDIN%% paaPbCopy"
