#!/usr/bin/env zsh
# 概要：psをcandidateとしてpecoしてkillする
ps aux | peco | awk '{ print $2 }'|pecoAfterAction \
  'kill -TERM' \
  'kill -INT' \
  'kill -HUP' \
  'kill -QUIT' \
  'kill -SIGILL' \
  'kill -KILL' \
  "paaInputCommandAny" \
  "%%STDIN%% pbcopy" \
  "%%STDIN%% paaTovim" \
  "%%STDIN%% pecoPipe"

