#!/usr/bin/env zsh
#概要：known_hostsなどからssh先をpecoして接続する
candidates=($(_sshSourceAction))
for candidate in $candidates; do
  echo $candidate
done | peco --prompt "[$0]"| sort | uniq | pecoAfterAction "pssh" \
                              "tcmd sftp" \
                              "tcmd redis-stat" \
                              "%%STDIN%% cat" \
                              "%%STDIN%% paaTovim" \
                              "%%STDIN%% pecoPipe" \
                              "%%STDIN%% paaPbCopy"

