#!/usr/bin/env zsh

#概要：rgしてpecoしてvimで開く
rg $@ --line-number | _pecoBeforeFilter | selector --prompt "[$0]" | awk -F : '{print "-c " $2 " " $1}' | \
  pecoAfterAction \
    "vi " \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% pecoPipe" \
    "%%STDIN%% cat" \
    "pbcopy "
