#!/usr/bin/env zsh
# 概要：psをcandidateとしてpecoしてkillする
ps aux | peco | awk '{ print $2 }'|pecoAfterAction \
  "%%STDIN%% paaKill -TERM" \
  "%%STDIN%% paaKill -INT" \
  "%%STDIN%% paaKill -HUP" \
  "%%STDIN%% paaKill -QUIT" \
  "%%STDIN%% paaKill -SIGILL" \
  "%%STDIN%% paaKill -KILL" \
  "paaInputCommandAny" \
  "%%STDIN%% cat" \
  "%%STDIN%% pbcopy" \
  "%%STDIN%% paaTovim" \
  "%%STDIN%% paaPbCopy"

