#!/usr/bin/env zsh
#概要：known_hostsなどからssh先をpecoして複数同時接続して各paneをtmuxで同期する
candidates=($(_sshSourceAction))
for candidate in $candidates; do
  echo $candidate
done | peco | sort | uniq | pecoAfterAction "tssh" \
                              "%%STDIN%% pbcopy"

