#!/usr/bin/env zsh

#概要：git statusで出てくるファイルをいろいろする
workDir=$(pwd)
gitRootDir=$(git rev-parse --show-toplevel)
cd "$gitRootDir"
(git status --porcelain;git ls-files) | peco | perl -pe 's/^( ?D )|( ?MM )|( ?M )|( ?A )|(\?\? )//g' |perl -pe 's/^ +//g'|\
  pecoAfterAction "git add" \
    "git checkout" \
    "git reset HEAD" \
    "git diff" \
    "git diff --cached" \
    "git rm" \
    'vimdiff' \
    'cat'\
    'open' \
    "%%STDIN%% pbcopy" \
    "vi" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% paaSafeRm" \
    "paaInputCommandAny"
_executeTmuxBuffer "cd '$workDir'"

