#!/usr/bin/env zsh

#概要：git statusで出てくるファイルをいろいろする
workDir=$(pwd)
gitRootDir=$(git rev-parse --show-toplevel)
cd "$gitRootDir"
(git status --porcelain;git ls-files) | peco | awk 'BEGIN{FS= " "}{print $NF}'| \
  pecoAfterAction "git add" \
    "git checkout" \
    "git reset HEAD" \
    "git diff" \
    "git diff --cached" \
    "git rm" \
    'vimdiff' \
    'open' \
    "%%STDIN%% pbcopy" \
    "vi" \
    "%%STDIN%% paaSafeRm" \
    "paaInputCommandAny"
_executeTmuxBuffer "cd '$workDir'"

