#!/usr/bin/env zsh
#概要：git log を１行で表示していろいろする
git log --date=iso --pretty=format:'%h - <%an> %ce - %cd - %d %s ' --abbrev-commit \
| selector --prompt "[$0]"| awk 'BEGIN{FS= " "}{print $1}'| \
  pecoAfterAction "%%STDIN%% pbcopy" \
    "git show" \
    "git checkout" \
    "git checkout " \
    "git checkout -t" \
    "git diff" \
    "git vdiff" \
    "git revert" \
    "git rebase -i" \
    "git reset --soft" \
    "git reset --hard" \
    "hub browse -- commit/" \
    "%%STDIN%% cat" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% paaPbCopy" \
    "%%STDIN%% pecoPipe" \
    "paaInputCommandAny"

