#!/usr/bin/env zsh
#概要： minion nodeに対してなにかする やつ
function getIp() {
  while read node;do
    kubectl describe node $node|egrep Addresses:|awk '{print $NF}'|awk 'BEGIN{FS=","}{print $1}'|perl -pe 's/^$//g'
  done
}

function nodeSsh() {
  getIp | pecoAfterAction pssh
}

function nodeSftp() {
  getIp | pecoAfterAction sftp
}

kubectl get po -o wide | peco | awk '{print $NF}'|sort | uniq | \
  pecoAfterAction \
    "kubectl describe node " \
    "kubectl get node " \
    "kubectl get node --output=json " \
    "kubectl get node --output=yaml " \
    "%%STDIN%% nodeSsh" \
    "%%STDIN%% nodeSftp" \
    "%%STDIN%% cat" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% pecoPipe" \
    "%%STDIN%% pbcopy"
