#!/usr/bin/env zsh
#概要：git branchにたいしていろいろする
(git branch |perl -pe 's/^\* //g';git branch -r;git tag )|perl -pe 's/^ +//g'| peco | awk 'BEGIN{FS= " "}{print $NF}'| \
  pecoAfterAction "git checkout" \
    "git checkout -t" \
    "git branch -d" \
    "git branch -D" \
    "git diff" \
    "git reset --soft" \
    "git reset --hard" \
    "git push origin" \
    "git pull origin" \
    "%%STDIN%% pbcopy" \
    "paaInputCommandAny"

