#!/usr/bin/env zsh

locate $@ | peco | pecoAfterAction "vi" \
  "cd" \
  'zip -e ./archive.$(date +%Y%m%d%H%M%S).zip' \
  'tar cvfz ./archive.$(date +%Y%m%d%H%M%S).tar.gz' \
  'vimdiff' \
  'less +F'\
  'cat'\
  'zcat'\
  'gzcat'\
  'open' \
  "%%STDIN%% paaSafeRm" \
  "paaInputCommandAny" \
  "%%STDIN%% pbcopy" \
  "%%STDIN%% paaTovim" \
  "%%STDIN%% paaExecuteAsCommand"

