#!/usr/bin/env zsh

#概要：agしてpecoしてvimで開く
ag $@ | _pecoBeforeFilter | peco --prompt "[$0]" | awk -F : '{print "-c " $2 " " $1}' | \
  pecoAfterAction \
    "vi" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% pecoPipe" \
    "%%STDIN%% cat" \
    "pbcopy"
