#!/usr/bin/env zsh

# 概要: lsしてpecoしてアクションする
searchPath=$@
if [[ -z $searchPath ]]; then
  searchPath="."
fi
if [[ $searchPath != "." && ! $searchPath  =~ "/$" ]]; then
  searchPath=$searchPath/
fi

find $searchPath -maxdepth 0 -print0 |xargs -0 ls -al | \
  peco | perl -lane 'print "@F[8..$#F]"' | awk 'BEGIN{FS="->"}{print $NF}' |pecoAfterAction "vi" \
    "cd" \
    'zip -e ./archive.$(date +%Y%m%d%H%M%S).zip' \
    'tar cvfz ./archive.$(date +%Y%m%d%H%M%S).tar.gz' \
    'vimdiff' \
    'open' \
    "%%STDIN%% paaSafeRm" \
    "paaInputCommandAny" \
    "%%STDIN%% pbcopy" \
    "%%STDIN%% paaExecuteAsCommand"
