#!/usr/bin/env zsh

# 概要: 任意のcandidateをpipeでつないでpecoしてafteractionするもの
_pecoBeforeFilter | peco | pecoAfterAction \
  "vi" \
  'zip -e ./archive.$(date +%Y%m%d%H%M%S).zip' \
  'tar cvfz ./archive.$(date +%Y%m%d%H%M%S).tar.gz' \
  "%%STDIN%% paaSafeRm" \
  "paaInputCommandAny" \
  "%%STDIN%% pbcopy" \
  "%%STDIN%% paaExecuteAsCommand"

