#!/usr/bin/env zsh
#概要： minion nodeに対してなにかする やつ
function getIp() {
  while read node;do
    kubectl describe node $node|egrep Addresses:|awk '{print $NF}'|awk 'BEGIN{FS=","}{print $1}'|perl -pe 's/^$//g'
  done
}

kubectl get po -o wide | peco | awk '{print $NF}'| getIp|\
  pecoAfterAction \
    "pssh" \
    "sftp" \
    "%%STDIN%% cat" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% pecoPipe" \
    "%%STDIN%% pbcopy"
