#!/usr/bin/env zsh

# 概要：cdrをpeco風味にやる
dirs -l|perl -pe 's# /#\n /#g'| _pecoBeforeFilter |peco | \
  pecoAfterAction \
    "cd" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% pecoPipe" \
    "%%STDIN%% cat" \
    "pbcopy"
