#!/usr/bin/env zsh
self=$0

kubectl get ingress --all-namespaces=true| selector --prompt "[$0]"| awk '{print $2}'|sort | uniq | \
  selectorAfterAction \
    "kubectl describe ingress " \
    "kubectl get ingress " \
    "kubectl get ingress --output=json " \
    "kubectl get ingress --output=yaml " \
    "kubectl edit ingress " \
    "%%STDIN%% cat " \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% selectorPipe" \
    "%%STDIN%% paaPbCopy"
