#!/usr/bin/env zsh
self=$0

func $self::removeAnsiColor() {
    sed "s,$(printf '\033')\\[[0-9;]*[a-zA-Z],,g"
}

func $self::connectVpn () {
    VPNS=( ${(@f)"$(< /dev/stdin)"} )
    for VPN in $VPNS; do
        echo "Connecting VPN: $VPN"
        gotunl -c $VPN
    done
    gotunl -l
}

func $self::closeVpn () {
    VPN=( ${(@f)"$(< /dev/stdin)"} )
    for VPN in $VPN; do
        echo "Closing VPN: $VPN"
        gotunl -d $VPN
    done
    gotunl -l
}

gotunl -l -o tsv | $self::removeAnsiColor |selector --prompt "[$0]"|awk '{print $1}' |selectorAfterAction \
  "%%STDIN%% $self::connectVpn " \
  "%%STDIN%% $self::closeVpn "
