#!/usr/bin/env zsh

# 概要： fd(fd-find)でファイル検索してselectorしてアクションする
# .gitignore と .agignore のパターンを尊重する
# worktree(.wt/)内にいる場合はignore制約を緩和する

local fd_opts=(--hidden --ignore-file ${HOME}/.agignore)
if [[ "$PWD" == */.wt/* ]]; then
  fd_opts=(--hidden --no-ignore-vcs --ignore-file ${HOME}/.agignore)
fi

command fd ${fd_opts[@]} $@ | _selectorBeforeFilter| selector --prompt "[$0]"| selectorAfterAction "vi " \
    "cd " \
    "yazi " \
    'zip -e ./archive.$(date +%Y%m%d%H%M%S).zip ' \
    'tar cvfz ./archive.$(date +%Y%m%d%H%M%S).tar.gz ' \
    'tar xvfz ' \
    'vimdiff ' \
    'less +F '\
    'cat '\
    'zcat '\
    'gzcat '\
    'gunzip '\
    'chmod +x '\
    'open ' \
    "%%STDIN%% cat" \
    "%%STDIN%% paaSafeRm" \
    "paaInputCommandAny" \
    "%%STDIN%% paaPbCopy" \
    "%%STDIN%% paaPbCopyFilename" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% selectorPipe" \
    "%%STDIN%% paaExecuteAsCommand"

