#!/usr/bin/env zsh

# 概要： fd(fd-find)でファイル検索してselectorしてアクションする
# .gitignore と .agignore のパターンを尊重する

command fd --hidden --ignore-file ${HOME}/.agignore $@ | _selectorBeforeFilter| selector --prompt "[$0]"| selectorAfterAction "vi " \
    "cd " \
    "yazi " \
    'zip -e ./archive.$(date +%Y%m%d%H%M%S).zip ' \
    'tar cvfz ./archive.$(date +%Y%m%d%H%M%S).tar.gz ' \
    'tar xvfz ' \
    'vimdiff ' \
    'less +F '\
    'cat '\
    'zcat '\
    'gzcat '\
    'gunzip '\
    'chmod +x '\
    'open ' \
    "%%STDIN%% cat" \
    "%%STDIN%% paaSafeRm" \
    "paaInputCommandAny" \
    "%%STDIN%% paaPbCopy" \
    "%%STDIN%% paaPbCopyFilename" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% selectorPipe" \
    "%%STDIN%% paaExecuteAsCommand"

