#!/usr/bin/env zsh
#概要：git branchにたいしていろいろする
(git branch |perl -pe 's/^\* //g';git branch -r;git tag )|_selectorBeforeFilter| perl -pe 's/^(origin.*)/\e[90m$1\e[0m/g' | selector --ansi --prompt "[$0]"| awk 'BEGIN{FS= " "}{print $NF}'| \
  selectorAfterAction "git checkout " \
    "git checkout -t " \
    "git branch -d " \
    "git branch -D " \
    "git diff " \
    "git vdiff " \
    "git reset --soft " \
    "git reset --hard " \
    "git rebase -i " \
    "git push origin " \
    "git push origin --force " \
    "git push origin --force-with-lease " \
    "git pull origin " \
    "gh pr view --web " \
    "git merge " \
    "%%STDIN%% cat" \
    "%%STDIN%% paaPbCopy" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% selectorPipe" \
    "paaInputCommandAny"

