#!/usr/bin/env zsh
self=$0

workon | _selectorBeforeFilter | selector --prompt "[$0]" | selectorAfterAction \
    "workon " \
    "rmvirtualenv " \
    "%%STDIN%% cat" \
    "paaInputCommandAny" \
    "%%STDIN%% paaPbCopy" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% selectorPipe" \
    "%%STDIN%% paaExecuteAsCommand"
