#!/usr/bin/env zsh

kubectl get rc | selector --prompt "[$0]"| awk '{print $1}'|sort | uniq | \
  selectorAfterAction \
    "kubectl describe rc " \
    "kubectl get rc " \
    "kubectl get rc --output=json " \
    "kubectl get rc --output=yaml " \
    "kubectl edit rc " \
    "%%STDIN%% cat" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% selectorPipe" \
    "%%STDIN%% paaPbCopy"
