#!/usr/bin/env zsh

#概要：mdfindしてselectorしてactionする
mdfind $@ | selector --prompt "[$0]"| selectorAfterAction "vi " \
  "cd " \
  'zip -e ./archive.$(date +%Y%m%d%H%M%S).zip ' \
  'tar cvfz ./archive.$(date +%Y%m%d%H%M%S).tar.gz ' \
  'tar xvfz ' \
  'vimdiff ' \
  'less +F '\
  'cat '\
  'zcat '\
  'gzcat '\
  'gunzip '\
  'chmod +x '\
  'open ' \
  "%%STDIN%% cat" \
  "%%STDIN%% paaSafeRm" \
  "paaInputCommandAny" \
  "%%STDIN%% paaPbCopy" \
  "%%STDIN%% paaPbCopyFilename" \
  "%%STDIN%% paaTovim" \
  "%%STDIN%% selectorPipe" \
  "%%STDIN%% paaExecuteAsCommand"

