#!/usr/bin/env zsh
#概要： podに対してなにかする やつ
self=$0

function $self::_convertPodToNodeIP() {
  while read pod ;do
    (kubectl get po $pod -o custom-columns=IP:status.hostIP|egrep -v '^IP$') &
  done
  wait
}
function $self::nodeSsh() {
  $self::_convertPodToNodeIP | sort | uniq | selectorAfterAction "pssh "
}

function $self::_k8sSh() {
  pods=("$@")
  tcmd kubectlSh $pods
}

function $self::k8sSh() {
  selectorAfterAction "$self::_k8sSh "
}

function $self::_k8sShContainer() {
  pods=("$@")
  kubectlShCon $pods
}

function $self::k8sShContainer() {
  selectorAfterAction "$self::_k8sShContainer "
}
function $self::k8sPortForward() {
	local podName=$1
	if [[ -z $podName ]]
	then
		return 1
	fi
	local port=$(kubectl get pod --output=json $podName |gron |grep -i containerport |perl -pe 's/.+=|;//g'|perl -pe 's/ //g'|tail -1)
	echo kubectl port-forward $podName $port:$port
	kubectl port-forward $podName $port:$port
}

function $self::k8sGetPodIP() {
	local podName=$1
	if [[ -z $podName ]]
	then
		return 1
	fi
  kubectl get pod --output=json $podName |gron|grep -i podip | perl -pe 's/.+=|;//g'|perl -pe 's/ //g' | perl -pe 's/"//g'
}

function $self::k8sGetPodIPToPbcopy() {
	local podName=$1
	if [[ -z $podName ]]
	then
		return 1
	fi
  podIp=$($self::k8sGetPodIP $podName)
  echo "pbcopied " $podIp
  echo $podIp | pbcopy
}

function $self::sternLogs() {
  pods=("$@")
  pods_regex=""
  for pod in $pods; do
    if [[ -z $pods_regex ]]; then
      pods_regex=$pod
    else
      pods_regex="$pods_regex|$pod"
    fi
  done
  echo stern $pods_regex
  stern $pods_regex
}

kubectl get po -o wide --all-namespaces=true| selector --prompt "[$0]"| awk '{print $2}'|sort | uniq | \
  selectorAfterAction \
    "kubectl describe pod " \
    "kubectl logs " \
    "kubectl logs -f " \
    "kubectl get pod " \
    "kubectl get pod --output=json " \
    "kubectl get pod --output=yaml " \
    "kubectl edit pod " \
    "kubectl sniff " \
    "$self::k8sGetPodIP " \
    "$self::k8sPortForward " \
    "$self::k8sGetPodIPToPbcopy " \
    "$self::sternLogs " \
    "%%STDIN%% $self::k8sSh" \
    "%%STDIN%% $self::k8sShContainer" \
    "%%STDIN%% $self::nodeSsh" \
    "%%STDIN%% cat" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% selectorPipe" \
    "%%STDIN%% paaPbCopy"
