#!/usr/bin/env zsh
#概要：git reflogにたいしていろいろやる
git reflog | selector --prompt "[$0]"| awk 'BEGIN{FS= " "}{print $1}'| \
  selectorAfterAction "%%STDIN%% pbcopy" \
    "git show " \
    "git checkout " \
    "git checkout " \
    "git checkout -t " \
    "git diff " \
    "git vdiff " \
    "git reset --soft " \
    "git reset --hard " \
    "%%STDIN%% cat" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% selectorPipe" \
    "%%STDIN%% paaPbCopy" \
    "paaInputCommandAny"

