#!/usr/bin/env zsh
self=$0

function $self::hubBrowse() {
  cid=$1
  hub browse -- commit/$cid
}

#概要：git log を１行で表示していろいろする
# フォーマット: 日時 メール メッセージ (refs) <TAB> ハッシュ
SELECTOR_POPUP_SIZE="90%,80%"
git --no-pager log --color=always --date=format:'%Y-%m-%d %H:%M' \
  --pretty=format:'%C(dim)%cd%Creset %C(cyan)%ce%Creset %s%C(magenta bold)%d%Creset%x09%C(yellow)%h%Creset' \
  --abbrev-commit \
| selector --ansi --prompt "[$0]" \
  --preview 'git show --stat --color=always {-1}' \
  --preview-window 'down:40%:wrap' \
  --bind '?:toggle-preview' \
| awk -F'\t' '{print $NF}' | \
  selectorAfterAction "%%STDIN%% pbcopy" \
    "git show " \
    "git checkout " \
    "git checkout " \
    "git checkout -t " \
    "git diff " \
    "git vdiff " \
    "git revert " \
    "git rebase -i " \
    "git reset --soft " \
    "git reset --hard " \
    "gh openpr " \
    "$self::hubBrowse " \
    "%%STDIN%% cat" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% paaPbCopy" \
    "%%STDIN%% selectorPipe" \
    "paaInputCommandAny"
unset SELECTOR_POPUP_SIZE
