#!/usr/bin/env zsh

#概要：rgしてselectorしてvimで開く
rg $@ --line-number | _selectorBeforeFilter | selector --prompt "[$0]" | awk -F : '{print "-c " $2 " " $1}' | \
  selectorAfterAction \
    "vi " \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% selectorPipe" \
    "%%STDIN%% cat" \
    "pbcopy "
