#!/usr/bin/env zsh

# 概要: 任意のcandidateをpipeでつないでselectorしてafteractionするもの
_selectorBeforeFilter | selector --prompt "[$0]"| selectorAfterAction \
  "vi " \
  'zip -e ./archive.$(date +%Y%m%d%H%M%S).zip ' \
  'tar cvfz ./archive.$(date +%Y%m%d%H%M%S).tar.gz ' \
  'tar xvfz ' \
  'vimdiff ' \
  'less +F '\
  'cat '\
  'zcat '\
  'gzcat '\
  'gunzip '\
  'chmod +x '\
  'open ' \
  "%%STDIN%% cat" \
  "%%STDIN%% paaSafeRm" \
  "paaInputCommandAny " \
  "%%STDIN%% paaPbCopy" \
  "%%STDIN%% paaPbCopyFilename" \
  "%%STDIN%% paaTovim" \
  "%%STDIN%% selectorPipe" \
  "%%STDIN%% paaExecuteAsCommand" \
  "%%STDIN%% paaPasteBuffer"

