#!/usr/bin/env zsh
self=$0

# 概要: lsしてselectorしてアクションする
function $self::_replaceChar() {
  # adhocなやつ
  perl -pe 's{ \Domain Users}{\DomainUsers}g'
  # | tee > /tmp/debug.log
}

# TODO Doesnt work
# $self::_interporatePath $searchPath
function $self::_interporatePath() {
  perl -e 'while(<STDIN>){
    if (not $ARGV[0] =~ /\./) {
      print "$ARGV[0]/$_";
    } else {
      print $_;
    }
  }' $1
}

searchPath=$@
if [[ -z $searchPath ]]; then
  searchPath="."
fi
if [[ $searchPath != "." && ! $searchPath  =~ "/$" ]]; then
  searchPath=$searchPath/
fi

# find $searchPath -maxdepth 0 -print0 |xargs -0 ls -al | _selectorBeforeFilter | $self::_replaceChar | \
# unbuffer ls -al $searchPath | $self::_replaceChar | \
unbuffer exa --icons --git -la --long --header $searchPath | $self::_replaceChar | \
  tail -r |selector --ansi --prompt "[$0]"| awk '{print $NF}' | $self::_interporatePath $searchPath | selectorAfterAction \
    "vi " \
    "gvim " \
    "cd " \
    'zip -e ./archive.$(date +%Y%m%d%H%M%S).zip ' \
    'tar cvfz ./archive.$(date +%Y%m%d%H%M%S).tar.gz ' \
    'tar xvfz ' \
    'vimdiff ' \
    'less +F '\
    'cat '\
    'bat '\
    'zcat '\
    'gzcat '\
    'gunzip '\
    'chmod +x '\
    'open ' \
    "git add " \
    "git restore " \
    "git restore --staged " \
    "git checkout " \
    "git reset HEAD " \
    "git diff " \
    "git vdiff " \
    "git diff --cached " \
    "git vdiff --cached " \
    "git rm " \
    'kubectl apply -f ' \
    "%%STDIN%% cat" \
    "%%STDIN%% paaSafeRm" \
    "paaInputCommandAny" \
    "%%STDIN%% paaPbCopy" \
    "%%STDIN%% paaPbCopyFilename" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% selectorPipe" \
    "%%STDIN%% paaExecuteAsCommand"
