#!/usr/bin/env zsh
self=$0

function $self::hubBrowse() {
  cid=$1
  hub browse -- commit/$cid
}

#概要：git log を１行で表示していろいろする
#
# git log --date=iso --pretty=format:'%h - <%an> %ce - %cd - %d %s ' --abbrev-commit \
git --no-pager log  --color=always --date=iso --pretty=format:'%x09%C(yellow)%h%Creset - <%x09%C(cyan bold)%an%Creset> %ce - %cd - %C(magenta reverse)%d%Creset %s ' --abbrev-commit \
| selector --ansi --prompt "[$0]"| awk 'BEGIN{FS= " "}{print $1}'| \
  selectorAfterAction "%%STDIN%% pbcopy" \
    "git show " \
    "git checkout " \
    "git checkout " \
    "git checkout -t " \
    "git diff " \
    "git vdiff " \
    "git revert " \
    "git rebase -i " \
    "git reset --soft " \
    "git reset --hard " \
    "gh openpr " \
    "$self::hubBrowse " \
    "%%STDIN%% cat" \
    "%%STDIN%% paaTovim" \
    "%%STDIN%% paaPbCopy" \
    "%%STDIN%% selectorPipe" \
    "paaInputCommandAny"

