return {
  {
    -- 高度なシンタックスハイライトと構文解析を提供するプラグイン
    'nvim-treesitter/nvim-treesitter',
    branch = 'main',
    cond = not vim.g.vscode,
    -- main ブランチは遅延ロード非対応
    lazy = false,
    build = ':TSUpdate',
    config = function()
      require('nvim-treesitter').install({
       "angular",
       "asm",
       "awk",
       "bash",
       "c",
       "c_sharp",
       "cmake",
       "comment",
       "commonlisp",
       "cpp",
       "css",
       "csv",
       "cue",
       "d",
       "dart",
       "diff",
       "dockerfile",
       "dot",
       "doxygen",
       "fish",
       "git_config",
       "git_rebase",
       "gitcommit",
       "gitignore",
       "go",
       "goctl",
       "gomod",
       "gosum",
       "gotmpl",
       "gowork",
       "graphql",
       "haskell",
       "haskell_persistent",
       "hcl",
       "helm",
       "html",
       "htmldjango",
       "http",
       "ini",
       "java",
       "javadoc",
       "javascript",
       "jinja",
       "jinja_inline",
       "jq",
       "json",
       "json5",
       "jsonnet",
       "julia",
       "kotlin",
       "lua",
       "luadoc",
       "luau",
       "make",
       "markdown",
       "markdown_inline",
       "mermaid",
       "nginx",
       "nickel",
       "objc",
       "ocaml",
       "ocaml_interface",
       "passwd",
       "perl",
       "php",
       "php_only",
       "phpdoc",
       "promql",
       "proto",
       "python",
       "r",
       "readline",
       "regex",
       "rego",
       "rst",
       "ruby",
       "runescript",
       "rust",
       "scala",
       "scheme",
       "scss",
       "sql",
       "ssh_config",
       "terraform",
       "toml",
       "tsv",
       "typescript",
       "typespec",
       "typoscript",
       "udev",
       "vim",
       "vimdoc",
       "vue",
       "xml",
       "yaml",
      })

      vim.api.nvim_create_autocmd('FileType', {
        group = vim.api.nvim_create_augroup('treesitter_start', { clear = true }),
        callback = function(args)
          -- パーサー未導入の filetype では失敗するので握りつぶす
          pcall(vim.treesitter.start, args.buf)
        end,
      })
    end,
  },
}


